[project]
name = "dailynews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "markdown>=3.10",
    "openai>=2.6.1",
    "requests>=2.32.5",
]
